<UL>
<li><a href="<?php echo $this->baseurl;?>/default/installation">Reexecutar instalador</a></li>
<li><a href="<?php echo $this->baseurl;?>/devel/index/resetdatabase">Reiniciar banco de dados</a></li>
<li><a href="<?php echo $this->baseurl;?>/devel/index/reverseengineer">Gerar objetos a partir do banco</a></li>
<li><a href="<?php echo $this->baseurl;?>/devel/index/crudgen">Gerar CRUD</a></li>
</UL>