<?php
class ProFlow_Model_DbTable_Usuario extends SanSIS_Model_Database_Abstract
{
protected $_schema = 'public';
protected $_name = 'usuario';
protected $_sequence = 'public.usuario_id_seq';

protected $_primary = array (
  0 => 'id',
);

protected $_cols = array (
  0 => 'id',
  1 => 'login',
  2 => 'senha',
  3 => 'nome',
  4 => 'sobrenome',
  5 => 'cargo',
  6 => 'endereco',
  7 => 'numero',
  8 => 'complemento',
  9 => 'bairro',
  10 => 'cep',
  11 => 'telefone',
  12 => 'email',
  13 => 'id_pais',
  14 => 'id_uf',
  15 => 'id_cidade',
  16 => 'id_departamento',
  17 => 'status_tupla',
);

protected $_metadata = array (
  'id' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'id',
    'COLUMN_POSITION' => 1,
    'DATA_TYPE' => 'int4',
    'DEFAULT' => 'nextval(\'public.usuario_id_seq\'::regclass)',
    'NULLABLE' => false,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => true,
    'PRIMARY_POSITION' => 1,
    'IDENTITY' => true,
  ),
  'login' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'login',
    'COLUMN_POSITION' => 2,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '30',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'senha' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'senha',
    'COLUMN_POSITION' => 3,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '128',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'nome' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'nome',
    'COLUMN_POSITION' => 4,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '100',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'sobrenome' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'sobrenome',
    'COLUMN_POSITION' => 5,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '100',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'cargo' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'cargo',
    'COLUMN_POSITION' => 6,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => '100',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'endereco' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'endereco',
    'COLUMN_POSITION' => 7,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => '512',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'numero' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'numero',
    'COLUMN_POSITION' => 8,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => '10',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'complemento' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'complemento',
    'COLUMN_POSITION' => 9,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => '100',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'bairro' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'bairro',
    'COLUMN_POSITION' => 10,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => '100',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'cep' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'cep',
    'COLUMN_POSITION' => 11,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => '10',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'telefone' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'telefone',
    'COLUMN_POSITION' => 12,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '14',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'email' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'email',
    'COLUMN_POSITION' => 13,
    'DATA_TYPE' => 'varchar',
    'DEFAULT' => NULL,
    'NULLABLE' => false,
    'LENGTH' => '100',
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'id_pais' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'id_pais',
    'COLUMN_POSITION' => 14,
    'DATA_TYPE' => 'int4',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'id_uf' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'id_uf',
    'COLUMN_POSITION' => 15,
    'DATA_TYPE' => 'int4',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'id_cidade' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'id_cidade',
    'COLUMN_POSITION' => 16,
    'DATA_TYPE' => 'int4',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'id_departamento' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'id_departamento',
    'COLUMN_POSITION' => 17,
    'DATA_TYPE' => 'int4',
    'DEFAULT' => NULL,
    'NULLABLE' => true,
    'LENGTH' => 4,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
  'status_tupla' => 
  array (
    'SCHEMA_NAME' => 'public',
    'TABLE_NAME' => 'usuario',
    'COLUMN_NAME' => 'status_tupla',
    'COLUMN_POSITION' => 18,
    'DATA_TYPE' => 'bit',
    'DEFAULT' => 'B\'1\'::"bit"',
    'NULLABLE' => false,
    'LENGTH' => -1,
    'SCALE' => NULL,
    'PRECISION' => NULL,
    'UNSIGNED' => NULL,
    'PRIMARY' => false,
    'PRIMARY_POSITION' => NULL,
    'IDENTITY' => false,
  ),
);

}
?>