<p>Para que seja possível realizar a instalação, alterações de código, e uso do ProFlow, é preciso concordar com o termos de 
licenciamento abaixo.</p>

<p>Caso esteja em desacordo com tais termos, é possível também a obtenção de licenciamento em modelo comercial, cuja única diferença, 
é a não necessidade de compartilhamento do código alterado por sua corporação. Porém, neste caso, fica também vetada toda e qualquer
transferência, cessão, aluguel ou venda de serviços ou sistemas que tenham por base o uso direto ou indireto deste código.</p>

<p>A configuração do ProFlow para suas dependências tecnológicas não é vista como alteração de código. E para sua segurança, as
informações de configuração devem ser mantidas em sigilo e nunca serem compartilhadas com terceiros. A equipe do ProFlow não se
responsabiliza pelo acesso indevido a quaisquer informações sobre a configuração ou conteúdo cadastrado em seu banco de dados
utilizando esta ferramenta.</p>

<p>Para maiores informações sobre licenciamento em modelo comercial, procure diretamente a SanSIS. Nenhuma outra empresa está
autorizada a licenciar esta aplicação sob modelo comercial, exceto a SanSIS, ou empresas indicadas diretamente pela SanSIS como
intermediadoras.

<?php echo $this->form;?>