<p>Para finalizarmos o processo de instalação, é necessário criar um super-usuário para poder acessar a aplicação após a configuração.</p>
<p>Este usuário tem privilégios especiais, por isso é importante que ele só seja utilizado quando realmente for necessário</p>
<p>Após a configuração do sistema, crie uma conta de Administrador para gerenciar seus usuários e configurações.</p>

<?php echo $this->form;?>